### ISSUE TITLE
Add UI for when MainPlayer selects a key

### ISSUE THREAD

**Issue by camillac** [camillac/CatBurglars#29]
For now, instead of doing it based selecting keys and submitting after all three are selected, we'll have a UI that simply works when the player clicks the key, it'll send a socket signal back.

We'll develop the UI after the MVP is due.

**Comment by camillac** [comment]
When a MainPlayer selects a key, either display an x if incorrect or a check if correct at the top of the screen that fades after some time

**Comment by shafali731** [comment]
I didn't do this by socket connection but did it within the scene itself
